jsverse/transloco

projects/ngneat/transloco/package.json

Peer dependencies were missing. This will cause errors on certain services. See: https://bundlephobia.com/result?p=@ngneat/transloco
This commit adds @angular/core and rxjs as peerDependencies of the library.

Add peerDependencies to package.json

---

README.md
projects/ngneat/transloco/src/lib/tests/transloco.mocks.ts
projects/ngneat/transloco/src/lib/tests/transloco.service.spec.ts
projects/ngneat/transloco/src/lib/transloco.config.ts
projects/ngneat/transloco/src/lib/transloco.service.ts

add option to allow empty keys
Closes: #42
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat: 🎸 missing-handler

---

README.md
projects/ngneat/transloco/src/lib/tests/transloco.directive.spec.ts
projects/ngneat/transloco/src/lib/transloco.directive.ts
src/app/scope-sharing/scope-sharing.component.html
src/app/scope-sharing/scope-sharing.component.ts
src/assets/i18n/en.json
src/assets/i18n/es.json

Adds ability to limit a translation to a nested property so you don't have to write the full path in each translation.
Given this:
```typescript
{
common: {
foo: 'Foo',
bar: 'Bar'
},
dashboard: {
title: 'Title',
desc: 'Desc'
}
}
```
you can do
```html
<ng-container *transloco="let t; limit: 'dashboard'">
<h1>{{ t.title }}</h1>
<p>{{ t.desc }}</p>
</ng-container>
```
```
[ ] Bugfix
[x] Feature
```
Issue Number: #41
```
[ ] Yes
[x] No
```
1. not sure about the naming
2. …

feat(directive): add ability to read nested property

---

README.md

Fix typo in README.md: toods -> todos
```
[ ] Bugfix
[ ] Feature
```
Typo in README.md
Fixed typo
```
[ ] Yes
[x] No
```

docs: ✏ fix typo

---

projects/ngneat/transloco-messageformat/README.md

```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
The readme for the messageformat plugin had a duplicate block of code.
Removed duplicate code block.
```
[ ] Yes
[x] No
``

docs(messageformat): cleanup docs and remove duplication

---

projects/ngneat/transloco-messageformat/README.md

It should be `customFormatters` instead of `formatters`.
```
[ ] Bugfix
[ ] Feature
```
Information in Readme.MD not consistant with the source code.
```
[ ] Yes
[x] No
```

Inconsistance with MessageFormat.Options interface

---

README.md

```
[ ] Bugfix
[ ] Feature
```
Links to gitbook in the docs right now redirect to "page not found".
For example:
https://app.gitbook.com/@netbasal/s/transloco/general/blog-posts
redirects you to
https://netbasal.gitbook.io/transloco/ssrSpaces/spaces/transloco/general/blog-posts
which doesn't exist and you get "page not found" message.
Changed links to https://netbasal.gitbook.io/transloco/
```
[ ] Yes
[ ] No
```

Fix gitbook links in docs

---

projects/ngneat/transloco/src/lib/transloco-testing.module.ts

fix: 🐛 remove missing keys warnings in tests

---

projects/ngneat/transloco/src/lib/transloco-missing-handler.ts
projects/ngneat/transloco/src/lib/transloco.service.ts

```
[x] Bugfix
[x] Feature
```
- There is no access to `activeLang` in the missing key handler. 
- `defaultLang` and `availableLangs` could be out-of-date
Issue Number: Closes #164
- Include `activeLang` in the info object passed to `MissingHandler.handle()`
- Pass up-to-date versions of aforementioned properties
```
[ ] Yes
[x] No
```
**Questions**  
I searched for a way to update the docs at <https://netbasal.gitbook.io/transloco/hack-the-library/transloco-missing-han …

feat: access to active language and up-to-date config in MissingHandler

---

projects/ngneat/transloco-scoped-libs/index.js
projects/ngneat/transloco-scoped-libs/utils.js

close #176 
This PR adds support for multiple destinations for `scoped-lib-extractor`
`transloco.config.js`:
```js
module.exports = {
rootTranslationsPath: 'src/assets/i18n/',
langs: ['en', 'es'],
keysManager: {},
scopedLibs: [{
src: './projects/side-lib',
dist: ['./projects/spa/src/assets/i18n', './src/assets/i18n/']
}]
};
```

plugin: 💥 scoped-lib-extractor support multi destintations

---

projects/ngneat/transloco/src/public-api.ts

```
[x] Bugfix
[ ] Feature
```
I noticed the TranslocoMissingHandlerData was not exported correctly which lead to it being importable only through `import { TranslocoMissingHandlerData } from '@ngneat/transloco/lib/transloco-missing-handler';`.
The interface will be importable through `import { TranslocoMissingHandlerData } from '@ngneat/transloco';`.
```
[ ] Yes
[x] No
```

fix: add TranslocoMissingHandlerData to types

---

cypress/integration/full-cycle.spec.ts
cypress/integration/lazy.ts
projects/ngneat/transloco/src/lib/scope-resolver.ts
projects/ngneat/transloco/src/lib/tests/directive/multi-scope-alias.spec.ts
projects/ngneat/transloco/src/lib/tests/pipe/pipe.spec.ts
projects/ngneat/transloco/src/lib/tests/transloco.mocks.ts
projects/ngneat/transloco/src/lib/transloco.directive.ts
projects/ngneat/transloco/src/lib/transloco.pipe.ts
projects/ngneat/transloco/src/lib/transloco.service.ts
projects/ngneat/transloco/src/lib/types.ts
src/app/app-routing.module.ts
src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.html
src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.spec.ts
src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.ts
src/app/lazy-multiple-scopes/lazy-multiple-scopes.module.ts
src/app/lazy/lazy.module.ts
src/app/transloco-testing.module.ts
vscode/extractor/README.md

```
[ ] Bugfix
[X] Feature
```
It does not support `multi: true` when providing TRANSLOCO_SCOPE, meaning you can only have one scope per module/component
Fix for https://github.com/ngneat/transloco/issues/181. This makes it possible to provide multiple translate scopes to a module or component. Works with structural directives and pipe.
```
[ ] Yes
[X] No
```

fix: Provide multiple values for TRANSLOCO_SCOPE to support lazy loading multiple json files

---

projects/ngneat/transloco/src/lib/tests/pipe/pipe-integration.spec.ts
projects/ngneat/transloco/src/lib/tests/transloco-config-provider.spec.ts
projects/ngneat/transloco/src/lib/tests/transloco.mocks.ts
projects/ngneat/transloco/src/lib/transloco-testing.module.ts
projects/ngneat/transloco/src/lib/transloco.config.ts
projects/ngneat/transloco/src/public-api.ts
schematics/src/ng-add/index.ts
src/app/app.module.ts

Closes #195
```
[ ] Bugfix
[x] Feature
```
Issue Number: #195
Adds new `provideTranslocoConfig` method as described in the issue.
This method can be used to provide the `TRANSLOCO_CONFIG` provider to the `providers` array. For example:
```
providers: [
httpLoader,
provideTranslocoConfig({
prodMode: environment.production,
availableLangs: [{ id: 'en', label: 'English' }, { id: 'es', label: 'Spanish' }],
reRenderOnLangChange: true,
fallbackLang: 'es',
defaultLang: 'en', …
```

feat(transloco): implement provideTranslocoConfig method

---

projects/ngneat/transloco-scoped-libs/cli.js
projects/ngneat/transloco-scoped-libs/index.js

Adds an option to the transloco-scoped-libs that allows not to modify the .gitignore file at all
resolves #216
```
[ ] Bugfix
[x] Feature
```
https://github.com/ngneat/transloco/issues/216
Issue Number: 216
A new option to the transloco-scoped-libs tool has been added. Setting it to true results in not modifying gitignore file at all
```
[ ] Yes
[x] No
```

feat(transloco-scoped-libs): adds modifyGitignore option

---

libs/transloco-locale/src/lib/pipes/transloco-currency.pipe.ts
libs/transloco-locale/src/lib/pipes/transloco-date.pipe.ts
libs/transloco-locale/src/lib/pipes/transloco-decimal.pipe.ts
libs/transloco-locale/src/lib/pipes/transloco-locale.pipe.ts
libs/transloco-locale/src/lib/pipes/transloco-percent.pipe.ts

moved angular feature (onDestroy) down to children classes
see https://angular.io/guide/migration-undecorated-classes#im-a-library-author-should-i-add-the-directive-decorator-to-base-classes
```
[x] Bugfix
[ ] Feature
```
Upgrading to angular 9 causes issues with transloco-locale when running tests or in jit mode.
```
Error: Directive TranslocoCurrencyPipe has no selector, please add it!
Directive TranslocoDatePipe has no selector, please add it!
Directive …
```

plugin(angular9): fix issue with transloco-locale and angular 9

---

schematics/src/migrate/ngx-translate-migration.ts

```
[x] Bugfix
[ ] Feature
```
If there is a module called `AbTranslateModule`, it currently gets replaced with `AbTranslocoModule`. 
This change modifies the regex so that it doesn't match "TranslateModule" if it's preceded by any letter character.
```
[ ] Yes
[x] No
```
You can see the updated regex and a few tests here:
https://regexr.com/530id
This is important for our use-case because we want to use the migration to migrate pipes and other …

fix: exclude prefixedTranslateModule when migrating

---

projects/ngneat/transloco/src/lib/tests/directive/shared.ts
projects/ngneat/transloco/src/lib/tests/directive/structural-loading-tpl.spec.ts
projects/ngneat/transloco/src/lib/transloco.directive.ts

fix: 🐛 don't display loading template if translations were load

---

schematics/src/ng-add/files/transloco-module/transloco-root.module.__ts__
schematics/src/ng-add/index.ts

Prevent Angular CLI generator from asking module name when generating
items by putting transloco.module in its own folder
Closes: #318
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: 🐛 Put transloco.module in its own folder

---

projects/ngneat/transloco-locale/src/lib/helpers.ts
projects/ngneat/transloco-locale/src/lib/tests/pipes/transloco-date.pipe.spec.ts

Hi, this is my first time doing a PR. 
```
[x] Bugfix
[ ] Feature
```
Error in Firefox. No dates are displayed.
Fixes #324 
It works now again in Firefox.
```
[ ] Yes
[x] No
```
See for Reference
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/79#JavaScript

plugin (locale): Error when usingDatePipe in Firefox 79 with timeStyle

---

docs/docs/tools/scope-lib-extractor.mdx

just a minor correction in documentation, usage is without destructuring

docs: correction on usage in scope-lib-extractor.mdx

---

docs/docs/scope-configuration.mdx

```
[ ] Bugfix
[ ] Feature
```
A typo in [Scope Configuration](https://ngneat.github.io/transloco/docs/scope-configuration) page.
The typo is eliminated.
```
[ ] Yes
[x] No
```

docs: fix a typo in "Scope Configuration" page

---

cypress/integration/locale.ts
docs/docs/plugins/locale.mdx
projects/ngneat/transloco-locale/src/lib/tests/transloco-locale.service.spec.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.service.ts
src/app/locale/locale/locale.component.html
src/app/locale/locale/locale.component.ts

There is no clean way to retrieve solely the currency symbol. Therefore a pivot element was chosen to
create a formatted number. In that result the pivot element was removed to retrieve only the currency
symbol.
Depending on the locale the symbol can be on either the left or the right side of the number.
Fixes #339
```
[ ] Bugfix
[x] Feature
```
At the moment it is not possibly to retrieve solely the currency symbol of the currently set locale. 
Issue Number: #339 
The …

plugin: get the currency symbol for the currently set locale

---

cypress/integration/lazy.ts
cypress/integration/locale.ts
projects/ngneat/transloco-locale/src/lib/tests/pipes/transloco-date.pipe.spec.ts
src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.html

Some tests failed due to a missing localization of expected time values.
One e2e got removed because it isn't valid anymore.
Please check whether the localized expected time values work in your timezone as well.
```
[x] Bugfix
[ ] Feature
```
Some unit tests failed under the wrong time zone.
Some e2e tests failed because of various reasons:
* legacy
* wrong time zone
All unit tests and e2e tests run fine.
```
[ ] Yes
[x] No
```

fix(tests): fix failing unit and e2e tests

---

projects/ngneat/transloco-scoped-libs/index.js
projects/ngneat/transloco-scoped-libs/package-lock.json
projects/ngneat/transloco-scoped-libs/package.json

I found it a bit hard trying to track down bad package.json files when using this across a large project with many scopes. This change clarifies which package.json has failed the check for i18n config.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Console output when bad package.json is used only says `package.json missing ...`
Output contains package.json location by using the `lib.src` parameter.
```
[ ] Yes
[x] No
```

fix: directly specify location of package.json missing i18n config

---

docs/docs/unit-testing.mdx

Don't suggest naming the Transloco testing module file name as `.spec` , as this will throw an error for not having any real test inside it.
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: rename Transloco testing module filename

---

docs/docs/translation-api.mdx
projects/ngneat/transloco/src/lib/tests/service/setTranslationKey.spec.ts
projects/ngneat/transloco/src/lib/transloco.service.ts

```
[ ] Bugfix
[x] Feature
```
When setting the translation using ``setTranslationKey`` from TranslocoService, there is no way to specify translation option. 
You can specify translation options in the  ``setTranslationKey`` method. It just passes them to the inner call of ``setTranslation``.
```
[ ] Yes
[x] No
```

feat: allow to specify options when setting translations by key

---

cypress/integration/home.ts
docs/docs/structural-directive.mdx
projects/ngneat/transloco/src/lib/tests/directive/structural.spec.ts
projects/ngneat/transloco/src/lib/transloco.directive.ts
src/app/on-push/on-push.component.html
src/app/on-push/on-push.component.spec.ts

Make currentLang available in the recommended approach, the structural directive, to prevent having to inject the service in instances where obtaining the language is the only required usage.
Closes ngneat/transloco#376
```
[ ] Bugfix
[x] Feature
```
Issue Number: #376 
Make currentLang available in the recommended approach, the structural directive, to prevent having to inject the service in instances where obtaining the language is the only required usage.
```
[ ] …
```

feat: 🎸 expose currentLang in structural directive

---

docs/src/css/custom.css

It changes the color of code samples included in the note sections of the documentation on dark mode.
Affected documentation pages : 
- [Installation](https://ngneat.github.io/transloco/docs/installation)
- [Language API](https://ngneat.github.io/transloco/docs/language-api)
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: style change
```
The code samples included into `::note` sections are hard to read on dark mode :
Issue Number: #475
The color of the code samples changed : 
```
[ ] Yes …
```

style(docs): make code samples into note sections more readable

---

projects/ngneat/transloco/src/lib/transloco.service.ts

Hey! I've noticed that `TranslocoService` is not getting GC'd when the app is destroyed, since cached values are capturing `this` (see code comments):

fix: allow `TranslocoService` to be garbage collected

---

projects/ngneat/transloco/src/lib/transloco.directive.ts

```
[ ] Bugfix
[x] Feature
```
Currently we can't override the `getTranslateFn` as it's `private`.
Issue Number:
Closes #489.
This changes `getTranslateFn` to be `protected` and so we can override it in order to make it work with the cases mentioned on #489.
```
[ ] Yes
[x] No
```

feat: add possibility of override `getTranslateFn`

---

projects/ngneat/transloco/src/lib/transloco.service.ts

```
[x] Bugfix
[ ] Feature
```
The transpiler changes language too late.
https://stackblitz.com/edit/ngneat-transloco-hsemz9
Steps to reproduce:
* Open console
* See `onLangChanged:` and `TRANSPILE:` logs
* Click Spanish/Russian language button. Translations loaded. Ok.
* Click English. The directive/pipe translations (2/3) use previous parser language. Not `en`.
* Click Russian. Same. + MF error (`few` with `en`).
Correct transpiler language.
```
[ ] …
```

fix: parser lang

---

docs/docs/installation.mdx
docs/docs/recipes/google-translate-integration.mdx
docs/docs/tools/scope-lib-extractor.mdx

fix ../../img/installation.gif
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```

🐛 fix img path

---

libs/transloco/src/lib/transloco.directive.ts

```
[ ] Bugfix
[X] Feature
```
Provide a type for the template context.
The implicit variable is typed as `TranslateFn`.
Before the type of the context was `any`.
Intellisense in VS code:
https://angular.io/guide/structural-directives#improving-template-type-checking-for-custom-directives
Does not introduce breaking changes but could create build failures if consumers do not respect the type.
```
[ ] Yes
[X] No
```

feat(transloco): 🎸 add a template context guard to directive

---

libs/transloco-scoped-libs/package.json

The typo in the main property is causing issues while importing the library, as the referenced files
does not exist.
```
[x] Bugfix
[ ] Feature
```
The `main` property in the `package.json` has a typo, which results in problems for TypeScript, as it can't find the given main file.
The library can be used with as `import` in TypeScript without an issue.
```
[ ] Yes
[x] No
```

fix(scoped-libs): remove typo in the main property

---

libs/transloco/src/lib/tests/service/translateObject.spec.ts
libs/transloco/src/lib/transloco.service.ts

```
[x] Bugfix
[ ] Feature
```
The following code throws "Cannot access 'scope' before initialization
`const result = translateService.translateObject(['object1', 'object2']);``
Issue Number: #576 
The code does not throw anymore
```
[ ] Yes
[x] No
```
When reverting my changes in the TranslocoService, the test failes with the error written above (to reproduce)

fix(service): key as array in translateObject throws

---

docs/docs/schematics/ng-add.mdx
libs/transloco-schematics/src/join/schema.json
libs/transloco-schematics/src/keys-manager/schema.json
libs/transloco-schematics/src/ng-add/schema.json
libs/transloco-schematics/src/split/schema.json
libs/transloco-schematics/src/tests/ng-add.spec.ts

- defaultProject was removed from the cli in angular 14
- this sets current working directory as default if --project argument is not specified
as recommended here : https://github.com/angular/angular-cli/issues/23470#issuecomment-1172240384
```
[x] Bugfix
[ ] Feature
```
When using the `ng add @ngneat/transloco` schematics with a newly created angular 14 project, it fails with the following error :
`Cannot read properties of undefined (reading 'projectType')`
Issue …

fix(schematics): set current directory as default project name

---

libs/transloco/src/lib/transloco.service.ts

Transloco - service:
To match the overloads of transteObject and selectTranslateObject.
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(service): add overload type in selectTranslateObject method

---

libs/transloco-locale/src/lib/helpers.ts
libs/transloco-locale/src/lib/tests/pipes/transloco-date.pipe.spec.ts
libs/transloco-locale/src/lib/tests/transloco-locale.service.spec.ts

Previously, the `TranslocoLocaleService` would only allow "zh-Hans" and "zh-hant" but not "zh-Hant". According to the IETF, script variants _should_ use title case but are not required to do so. This PR adds a RegExp that allows for case-insensitive script variants.
https://en.wikipedia.org/wiki/IETF_language_tag#Syntax_of_language_tags
```
[x] Bugfix
[ ] Feature
```
Issue Number: #636 
Any locale specifying a 4-letter script is accepted regardless of the letter case …

fix(transloco-locale): fixed letter case sensitivity for scripts

---

docs/docs/plugins/locale.mdx
libs/transloco-locale/src/index.ts

```
[ ] Bugfix
[x] Feature
```
When implementing custom transformers, you can only fallback to the default behaviour by code duplicating code from not exported internal functions of transloco-locale
Discussion Number: #435
`DefaultDateTransformer` and `DefaultNumberTransformer` are now exposed to public api, so that they can be referenced and used as fallback in custom implementations.
```
[ ] Yes
[x] No
```

feat(transloco-locale): expose default transformers (#435)

---

schematics/src/ng-migrate/ng-migrate.ts

This can happen in the presence of void elements.
```
[x] Bugfix
```
```
[ ] Yes
[x] No
```

fix(migrate): continue with null value instead of  TypeError: Cannot read property 'trim' of undefined.

---

libs/transloco/package.json

```
[x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
[x] Tests for the changes have been added (for bug fixes / features)
[x] Docs have been added / updated (for bug fixes / features)
```
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Version update
Issue Number: 674
@ngneat/transloco now relies on @ngneat/transloco-utils ^5.0.0
```
[ ] Yes
[x] No
```

Updated @ngneat/transloco-utils version to 5 in transloco deps.

---

libs/transloco-scoped-libs/src/lib/transloco-scoped-libs.ts

This change makes the program behave similarly with and without the --watch flag with respect to --skip-gitignore. Fixes issue #604.
Issue Number: #604

Add skipGitIgnoreUpdate to watch mode options

---

docs/docs/plugins/locale.mdx
libs/transloco-locale/src/lib/transloco-locale.types.ts

```
[ ] Bugfix
[X] Feature
```
There is no way of providing the option for number sign display without getting type errors or having to use `$any` in the template or `as any` or `as unknown as NumberFormatOptions` in the component.
The number sign display can be configured without workarounds or type errors.
```
[ ] Yes
[X] No
```

feat(transloco-locale): add sign display number format option

---

libs/transloco-locale/src/lib/pipes/transloco-currency.pipe.ts
libs/transloco-locale/src/lib/tests/pipes/transloco-currency.pipe.spec.ts

```
[ ] Bugfix
[x] Feature
```
Currently the `TranslocoCurrencyPipe` supports just `'code' | 'symbol' | 'name'`  currencyDisplay format options, while missing the `narrowSymbol` also suppored by `Intl.NumberFormat()`
Added an additional option supporting all the Intl.FormatNumber `currencyDisplay ` options.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#parameters
```
[ ] Yes
[x] No
```
The `narrowSymbol` …

feat(transloco): allow narrowSymbol display option

---

libs/transloco/src/lib/tests/transpiler.spec.ts
libs/transloco/src/lib/transloco.transpiler.ts

```
[x] Bugfix
[x] Feature
```
Issue Number: #589 
Translation strings work with more than one function provided by the FunctionalTranspiler.
```
[ ] Yes
[x] No
```

fix(transloco): allow multiple functions in translations

---

libs/transloco-locale/src/lib/helpers.ts

If you call `TranslocoLocaleService.setLocale` with the value of "es-419", it will not change the locale. 
"es-419" is allowed as a valid locale identifier.

fix(locale): 🐛 allow latin american spanish locale

---

README.md

The repo was transferred, meaning the links to the documentation have also changed. Currently it is not possible to access the documentation without manually updating the URL.
The links in the documentation now point to jsverse.github.io/ instead of ngneat.github.io/
Google (and likely other search engines, too) has not yet picked up on this change. Accessing the documentation at the moment is quite a hassle.

docs: links to documentation now point to jsverse.github.io

---

apps/transloco-playground/src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.ts
docs/docs/lazy-load/scope-configuration.mdx
libs/transloco/src/lib/transloco.providers.ts

Issue Number: https://github.com/ngneat/transloco/issues/708

feat(transloco): allow to provide multiple scopes via `provideTranslocoScope`

---

docs/docs/plugins/locale.mdx

There's no information about available values for date options nor where to find it. [Here](https://ngneat.github.io/transloco/docs/plugins/locale#date-format-options)
There is an information where to find available values for the date options.

docs: Link to date format options documentation

---

docs/docs/getting-started/config-options.mdx
docs/docs/lazy-load/scope-configuration.mdx
libs/transloco/src/lib/scope-resolver.ts
libs/transloco/src/lib/tests/scope-resolver.spec.ts
libs/transloco/src/lib/tests/service/setTranslation.spec.ts
libs/transloco/src/lib/transloco.config.ts
libs/transloco/src/lib/transloco.service.ts

Currently the `scope` is being altered by the `toCamelCase` helper method. This creates the issue that if you provide a `scope` where you would like to have the first character not to be changed OR just the casing in general you can only do this by providing an `alias`.
e.g `{ scope: 'FOOBAR', alias: 'FOOBAR' }`
This feature enabled the possibility to only provide the scope and the casing of it will not be altered, so you can just use this: `{ scope: 'FOOBAR' }` or `{ scope: 'F-OO-BaR' } --> will be transformed to `{ scope: 'FOOBaR' }`

feat(transloco): 🎸 add option to not change the casing of the provided scope

---

.github/workflows/ci.yml
.github/workflows/reviewdog.yml
.github/workflows/stale-issues.yml

Ci improvements

---

docs/docs/getting-started/angular-compatibility.mdx
docs/sidebars.js
docs/src/css/custom.css

docs: ✏️ Fix typo.

---

libs/transloco/src/lib/transloco-fallback-strategy.ts
libs/transloco/src/lib/transloco-lang.ts
libs/transloco/src/lib/transloco-loading-template.ts
libs/transloco/src/lib/transloco-missing-handler.ts
libs/transloco/src/lib/transloco-scope.ts
libs/transloco/src/lib/transloco.config.ts
libs/transloco/src/lib/transloco.interceptor.ts
libs/transloco/src/lib/transloco.loader.ts
libs/transloco/src/lib/transloco.transpiler.ts
libs/transloco/src/lib/types.ts

In this commit, we tree-shake injection token names in production by inlining the `ngDevMode` condition. This is the same approach that Angular uses.
See, for instance: https://tinyurl.com/4y9dxzsp (long GitHub URL).
`ngDevMode` cannot be extracted into a separate shared variable, as this would result in a separate runtime variable. The condition must always be inlined for the minifier to work correctly.

refactor(transloco): tree-shake injection token names in production

---

.github/workflows/ci.yml
package.json

Added the ability to install PRs more easily to test them before merging / releasing

ci: added pkg.pr.new

---

libs/transloco-utils/src/lib/transloco-utils.types.ts

No property  `keysManager.sort` in the `TranslocoGlobalConfig` interface.
Issue Number: #825
Expose property `keysManager.sort` for `TranslocoGlobalConfig` publically.
I'm not sure if there should be a documentation change for the page hosted under https://jsverse.gitbook.io/transloco/tools/keys-manager-tkm/options#transloco-config-file. I would apprechiate some input for this question.

chore(transloco-util): add keysManager.sort key to TranslocoGlobalConfig

---

apps/transloco-playground/src/app/home/home.component.html
apps/transloco-playground/src/app/home/home.component.ts
apps/transloco-playground/src/app/inline-loaders/inline-loaders.component.html
apps/transloco-playground/src/app/inline-loaders/inline-loaders.component.ts
libs/transloco/src/index.ts
libs/transloco/src/lib/tests/signal.spec.ts
libs/transloco/src/lib/transloco.signal.ts
tsconfig.json

Angular's new change detection is heavily signal-based but transloco does not provide a signal-based solution.
Issue Number: #781
This pull request introduces the `translateSignal` and `translateObjectSignal` functions, which allow you to get translated values ​​reactively.
```typescript
import {
TranslocoModule,
translateObjectSignal,
translateSignal,
} from '@jsverse/transloco';
@Component({
imports: [TranslocoModule],
template: `
<input ([ngModel])="dynamicKey" />
<div id="text">{{ translatedText() }}</div>
<div id="textObject">{{ translatedObject().title }}</div>
<div id="dynamic">{{ translatedDynamic() }}</div>
<button (click)="changeParam("🦄")">{{ translatedDynamic() }}</div>
`, …
```

feat(transloco): Added a `translateSignal` resource for reactive translation
