schematics/src/collection.json
schematics/src/migrate/index.ts
schematics/src/migrate/migration.ts
schematics/src/migrate/schema.json
schematics/src/migrate/schema.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore(schematics): add command for migration

---

schematics/package-lock.json
schematics/package.json
schematics/src/migrate/index.ts
schematics/src/migrate/schema.json
schematics/src/ng-add/index.ts
schematics/src/ng-add/schema.json
schematics/src/ng-add/schema.ts
schematics/src/utils/projects.ts

support project in ng-add
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(schematics): support project in ng-add

---

package-lock.json
schematics/package-lock.json
schematics/package.json
schematics/src/migrate/index.ts
schematics/src/migrate/migration.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: 🤖 migration script for ngx-translate

---

schematics/migration.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(migration): fix typo

---

ISSUE_TEMPLATE.md

```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
Added our stackblitz example to issue templates, so users could easily reproduce bugs
```
[ ] Yes
[x ] No
```

docs: ✏️ add stackblitz example to the issue-template

---

schematics/src/utils/ast-utils.ts

- [ x] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
```
[x ] Bugfix
[ ] Feature
```
Issue Number: #22 
fix failing `ng-add` for cases of default imports in `app.module.ts`.
```
[ ] Yes
[x ] No
```

fix: 🐛 schematics ng-add import-default bug

---

package.json
schematics/src/ng-add/files/http-loader/transloco.loader.__ts__
schematics/src/ng-add/index.ts
schematics/src/ng-add/schema.json
schematics/src/ng-add/schema.ts
schematics/src/utils/projects.ts

Added ng-add support for users that uses ssr

feat: 🎸 added ssr question to ng-add

---

schematics/src/ng-add/files/webpack-loader/transloco.loader.__ts__
schematics/src/ng-add/schema.json

- [x ] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
Remove loader and translate file format questions from ng-add.

refactor: 💡 remove loader and translate format ng-add questions

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(readme): add missing @

---

commitlint.config.js
projects/ngneat/transloco-messageformat/README.md
projects/ngneat/transloco-messageformat/src/lib/messageformat.config.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.module.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.spec.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.ts
projects/ngneat/transloco-messageformat/src/public-api.ts
src/app/app.module.ts

```
[ ] Bugfix
[x ] Feature
```
add configuration to format message

feat: 🎸 add configuration to format message

---

schematics/src/ng-add/index.ts
schematics/src/ng-add/schema.json

remove path question from ng-add
close #59

refactor: 💡 remove path question from ng-add

---

README.md

```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
No error is thrown by the compiler when trying to import language files even if there is a miss configuration. It breaks unit tests like so `Cannot read property 'myTranslation' of null`.  
Adding documentation about compiler configuration to synchronously load languages.
```
[ ] Yes
[X] No
```

Improve doc about synchronous lang loading

---

projects/ngneat/transloco-persist-lang/src/lib/persist-lang.service.ts
projects/ngneat/transloco-persist-translations/src/lib/transloco-persist-translations.service.ts
projects/ngneat/transloco-preload-langs/src/lib/transloco-preload-langs.module.ts
projects/ngneat/transloco/src/lib/transloco.directive.ts
projects/ngneat/transloco/src/lib/transloco.pipe.ts
projects/ngneat/transloco/src/lib/transloco.service.ts
src/app/app.component.ts

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
In some cases, there is no unsubscription, which makes memory leaks possible.
Always unsubscribe when necessary.
```
[ ] Yes
[x] No
```
OnDestroy lifecycle hook works in [services](https://angular.io/api/core/OnDestroy) and [modules](https://github.com/angular/angular/blob/master/packages/core/src/view/ng_module.ts#L222).
Even if the service is provided in root, it can be destroyed when the platform is [destroyed …

fix(core): lack of unsubscriptions

---

README.md
package-lock.json
projects/ngneat/transloco/src/lib/transloco.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: ✏️ add docs to programmatically scope translations

---

schematics/package-lock.json
schematics/package.json
schematics/src/collection.json
schematics/src/scope/index.ts
schematics/src/scope/schema.json
schematics/src/scope/schema.ts
schematics/src/utils/find-module.ts
schematics/src/utils/projects.ts
schematics/src/utils/translations.ts

Adding schematics for creating Transloco scope:
```
ng g @ngneat/transloco:scope my-transloco-scope-name
```
The command will:
- Create translation files based on the given name.
- Create/Update an angular module, with `TRANSLOCO_SCOPE` provider and `TranslocoModule`.

feat: 🤖 Add schematics for transloco scope

---

schematics/src/ng-add/index.ts

fix: 🐛 ng-add: fix hard coded fallbackLang

---

schematics/README.md

docs: ✏️ added README.md file for schematics

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: :pencil2: fix typo

---

projects/ngneat/transloco-optimize/README.md

```
[ ] Bugfix
[ ] Feature
```
The docs show the Transloco Config object containing `;` which when copied into a project causes syntax errors.
Change `;` to `,` allow easier copy and pasting of the config values into projects.
```
[ ] Yes
[x] No
```

docs(transloco-optimize): update readme to allow copy paste of config

---

schematics/package-lock.json
schematics/src/ng-add/index.ts
schematics/src/utils/translations.ts

skip translation files creation if they exist.
close #162

fix: 🐛 ng-add: skip translation files creation if exist

---

schematics/README.md

Some of the commands did not match the schema, and parts of the doc had typos.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs: ✏️ fix docs for schematics

---

projects/ngneat/transloco/src/lib/tests/pipe/pipe.spec.ts
projects/ngneat/transloco/src/lib/transloco.pipe.ts
src/assets/i18n/inline/en.json
src/assets/i18n/inline/es.json

fix: 🐛 pipe return empty string by default

---

projects/ngneat/transloco/src/lib/tests/service/fallbacks.spec.ts
projects/ngneat/transloco/src/lib/transloco.service.ts
src/app/inline-loaders/inline-loaders.module.ts

Closes: #210
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: 🐛 same fallback lang should not load again

---

projects/ngneat/transloco-messageformat/src/lib/messageformat.config.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.spec.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.ts
projects/ngneat/transloco/src/lib/transloco.service.ts
projects/ngneat/transloco/src/lib/transloco.transpiler.ts

plugin: 💥 message-format support run-time locale change

---

schematics/src/ng-migrate/ng-migrate.ts

fix issue with angular `i18n-attrubute` migration
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

propName => propValue

---

projects/ngneat/transloco-locale/src/lib/transloco-locale.types.ts

Added additional formatting options supported by the Intl.DateTimeFormat
- [ x ] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe:
```
Add's additional types
Issue Number: #245 
```
[ ] Yes
[ x ] No
```

Add additional options to date format types

---

projects/ngneat/transloco-locale/package.json
projects/ngneat/transloco-locale/src/lib/pipes/transloco-currency.pipe.ts
projects/ngneat/transloco-locale/src/lib/pipes/transloco-date.pipe.ts
projects/ngneat/transloco-locale/src/lib/pipes/transloco-decimal.pipe.ts
projects/ngneat/transloco-locale/src/lib/pipes/transloco-percent.pipe.ts
projects/ngneat/transloco-locale/src/lib/tests/mocks.ts
projects/ngneat/transloco-locale/src/lib/tests/pipes/transloco-currency.pipe.spec.ts
projects/ngneat/transloco-locale/src/lib/tests/transloco-locale.service.spec.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.module.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.service.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.transformers.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.types.ts
projects/ngneat/transloco-locale/src/public-api.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

plugin: 💥 locale: add localize API and transformers for date & number

---

projects/ngneat/transloco/src/lib/transloco-missing-handler.ts
projects/ngneat/transloco/src/lib/transloco.service.ts

```
[ ] Bugfix
[X] Feature
```
The missingHandler exported only expose key and data (config).
I added the params list because I want to be able to replace parameters even if my key is not found
optional parameter
```
[ ] Yes
[X] No
```
I don't know where to put the documentation for this change. If you tell me I would be happy to make the change.
For the tests, I can add an empty object to one of the exemple used to test the missing handler handle …

feat: 🎸 Add to missingHandler the translation's parameter(s)

---

projects/ngneat/transloco/src/lib/transloco.service.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: #287 
Only interpret language ids with slashes as scoped
```
[ ] Yes
[ ] No
```

fix: only interpret language ids with slashes as scoped

---

schematics/src/keys-manager/index.ts

fix: 🐛 update keys manager installation to latest version

---

cypress/integration/transpilers.ts
docs/docs/config-options.mdx
docs/docs/transpiler.mdx
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.spec.ts
projects/ngneat/transloco-messageformat/src/lib/messageformat.transpiler.ts
projects/ngneat/transloco/src/lib/tests/transloco.transpiler.spec.ts
projects/ngneat/transloco/src/lib/transloco.config.ts
projects/ngneat/transloco/src/lib/transloco.module.ts
projects/ngneat/transloco/src/lib/transloco.transpiler.ts
projects/ngneat/transloco/src/public-api.ts
src/app/app.module.ts
src/app/transpilers/transpilers.component.html
src/assets/i18n/transpilers/messageformat/en.json
src/assets/i18n/transpilers/messageformat/es.json

```
[ ] Bugfix
[x] Feature
```
You cannot specify your own regular expression for matching parameters. 
Issue Number: #323 
A new transpiler has been added that adds the possibility to specify your own regular expression for matching parameters. 
```
[ ] Yes
[x] No
```

feat: 🎸 Add interpolation to configuration

---

docs/docs/tools/optimize.mdx

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

doc(optimize): install as a dev dependency

---

docs/docs/translation-api.mdx

```
[ ] Bugfix
[ ] Feature
```
A typo in [Translation API](https://ngneat.github.io/transloco/docs/translation-api).
The typo is eliminated.
```
[ ] Yes
[x] No
```

docs: fix a typo in Translation API example

---

projects/ngneat/transloco-locale/package.json
projects/ngneat/transloco-locale/src/lib/helpers.ts

plugin: 💥 fix bcp-47 regex

---

README.md
docs/package.json

docs: ✏️ fix sample app link

---

docs/docs/additional-functionality.mdx
docs/docs/faq.mdx
docs/docs/unit-testing.mdx
docs/package-lock.json
docs/package.json
docs/src/css/custom.css
projects/ngneat/transloco/src/lib/transloco-testing.module.ts
projects/ngneat/transloco/src/public-api.ts
src/app/inline-loaders/inline/inline.component.spec.ts
src/app/lazy-multiple-scopes/lazy-multiple-scopes.component.spec.ts
src/app/on-push/on-push.component.spec.ts
src/app/transloco-testing.module.ts

Deprecated the `withLangs` function in the testing module and created `forRoot`
Closes: #250

fix: 🐛 service not initialized in testing module

---

projects/ngneat/transloco/src/lib/tests/service/fallbacks.spec.ts
projects/ngneat/transloco/src/lib/transloco.config.ts
projects/ngneat/transloco/src/lib/transloco.service.ts
projects/ngneat/transloco/src/lib/types.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #389
```
[ ] Yes
[x] No
```

fix: language fallback strategy

---

projects/ngneat/transloco-locale/README.md
projects/ngneat/transloco-locale/src/lib/tests/mocks.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.config.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.module.ts
projects/ngneat/transloco-locale/src/lib/transloco-locale.service.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #419
```
TranslocoLocaleModule.init({
defaultLocale: 'es-ES',
localeToCurrencyMapping: {}, // Avoid using predefined locale to currency and fallback to "defaultCurrency"
defaultCurrency: 'EUR'
})
```
```
[ ] Yes
[x] No
```

feat(locale): support default currency config

---

docs/docs/plugins/locale.mdx
projects/ngneat/transloco-locale/README.md

```
[ ] Bugfix
[ ] Feature
```
Angular template pipe had a missing bracket. 
Bracket is in place. Example copy-paste works.
```
[ ] Yes
[x] No
```

docs: add missing pipe attribute bracket

---

docs/docs/migration/angular.mdx

```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
N/A
```
[ ] Yes
[X] No
```

docs: add command to migrate from angular i18n

---

projects/ngneat/transloco/package-lock.json

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
High level security vulnerabilities are flagged by `npm audit` relating to nested dependencies on the `ansi-regex` package: https://snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908
Issue Number: #509
Updated dependencies which reference the problematic package version.
```
[ ] Yes
[x] No
```

fix: resolve ansi-regex vulnerability (#509)

---

docs/docs/tools/validator.mdx

- indicate validation package as dev dependency
- add missing assets in path for linting
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(validator): update install instructions and validation path

---

docs/docs/plugins/message-format.mdx

- [ X ] The commit message follows our guidelines: https://github.com/ngneat/transloco/blob/master/CONTRIBUTING.md#commit
- [ X ] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ X ] Documentation content changes
```
There is a repetition of phrase and weird "youIt" in the docs
Removes repeated text and "youIt"
```
[ ] Yes
[ X ] No
```

docs: fixes typo

---

docs/docs/additional-functionality.mdx
libs/transloco/src/index.ts
libs/transloco/src/lib/transloco.service.ts

Today I'm not able to translate an object from NgRx selectors (without dependency injection) 😢.
Export the `translateObject()` method from the `TranslocoService`, so it can be used as the `translate()` method.

feat(transloco): 💡export translateObject as a proxy to the TranslocoService.translateObject method

---

docs/docs/unit-testing.mdx

- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
[ ] Yes
[x ] No
```
Simple markdown update to link to the examples in the transloco source

fix broken links

---

libs/transloco/package.json

```
[x] Bugfix
[ ] Feature
```
Issue Number: #630
```
[ ] Yes
[x] No
```

fix(dependencies): update fs-extra and glob dependencies

---

apps/transloco-playground-e2e/src/integration/transpilers.ts
apps/transloco-playground/src/app/transpilers/transpilers.component.html
apps/transloco-playground/src/assets/i18n/transpilers/messageformat/en.json
apps/transloco-playground/src/assets/i18n/transpilers/messageformat/es.json
libs/transloco/src/lib/transloco.service.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: #633
Send lang changing event to transpiler before event to transloco pipe.
```
[ ] Yes
[x] No
```

fix(#633) - fix message format delay

---

docs/docs/recipes/google-translate-integration.mdx

typo
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(docs): fix typo in google-translate-integration.mdx

---

docs/docs/getting-started/installation.mdx
libs/transloco/src/index.ts
libs/transloco/src/lib/transloco-testing.module.ts
libs/transloco/src/lib/transloco.config.ts
libs/transloco/src/lib/transloco.module.ts
libs/transloco/src/lib/transloco.providers.ts

I moved the providers and added functions to work with Standalone Components.
```
[ ] Bugfix
[x] Feature
```
Issue Number: #614 
`provideTransloco` can be used to setup Transloco in an Standalone Setup.
```
[ ] Yes
[x] No
```

refactor(transloco): move providers to functions

---

BREAKING_CHANGES.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(breaking_changes): fix typo on messageformat section

---

libs/transloco-schematics/src/split/index.ts
libs/transloco-schematics/src/tests/split.spec.ts

Issue Number: #695 
Split schematic updates subfolders

fix(#695) Split schematic doesn't update subfolders

---

libs/transloco-preload-langs/src/lib/preload-langs.service.ts

Using the module causes the following error:
> nullinjectorerror: No provider for TranslocoPreloadLangsService!
Issue Number: #726

fix(preload-langs): 🐛 provide in root injector

---

docs/docs/recipes/google-translate-integration.mdx

The example code had a typo, it should now compile but also using the Find function in the browser now makes the code easier to search to see what's going on
Typo fixed

docs(utils): ✏️ Fixed a typo in the code example

---

libs/transloco-schematics/src/migrate/ngx-translate-migration.ts
libs/transloco-schematics/src/tests/ngx-translate-migration.spec.ts

fix(transloco-schematics): fixed file matching on Windows OS

---

libs/transloco/CHANGELOG.md

docs(transloco): add link to commit in changelog

---

@types/angular-globals/index.d.ts
apps/transloco-playground/src/test-setup.ts
apps/transloco-playground/tsconfig.app.json
libs/transloco-locale/src/test-setup.ts
libs/transloco-messageformat/src/test-setup.ts
libs/transloco-persist-lang/src/test-setup.ts
libs/transloco-persist-translations/src/test-setup.ts
libs/transloco/src/lib/transloco-fallback-strategy.ts
libs/transloco/src/lib/transloco-lang.ts
libs/transloco/src/lib/transloco-loading-template.ts
libs/transloco/src/lib/transloco-missing-handler.ts
libs/transloco/src/lib/transloco-scope.ts
libs/transloco/src/lib/transloco.config.ts
libs/transloco/src/lib/transloco.interceptor.ts
libs/transloco/src/lib/transloco.loader.ts
libs/transloco/src/lib/transloco.transpiler.ts
libs/transloco/src/lib/types.ts
libs/transloco/src/test-setup.ts
libs/transloco/tsconfig.lib.json

✅ Closes: #842
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
Issue Number: #842

fix(transloco): 🐛 remove ngDevMode global declaration

---

blog-posts/from-the-community.md

Added our Transloco tutorial.
It covers the basic and explains how to use BabelEdit to easily manage your translations.
Does not display our tutorial :-)
It displays our tutorial...

docs: update from-the-community.md - Added new tutorial

---

libs/transloco-locale/package.json
libs/transloco-locale/src/lib/transloco-locale.service.ts

feat(transloco-locale): Proposal: Improve Locale Detection Logic in TranslocoLocaleService

---

libs/transloco/ng-package.json
libs/transloco/package.json

#871
Moved to a dependency instead of a peer dep

fix: @jsverse/utils as a dependency
